### ISSUE TITLE
SUGGESTION: Add Percent Change Column to DT Table

### ISSUE THREAD

**Issue by jkorevaar** [oneacrefund/shiny_power#4]
I'd suggest we add a column to the table on the DT Tab so that you see both Magnitude Change and Percentage Change for both selections (e.g. both columns always appear). 

Right now, when you select Percentage Change, the table shows the results in Magnitude Change. This makes it a little less user-friendly as you first need to manually convert your Percentage Change back to a magnitude change to interpret the results.

**Comment by mattlowes** [comment]
Added.
